SAVE_VIDEO: True
SEED: 42
STEPS: 1000
num_envs: 256
controller: ik

# asset
asset_root: ../assets
asset_file: urdf/ycb/025_mug/025_mug_new.urdf

# robot
franka_asset_file: urdf/franka_description/robots/franka_panda.urdf